library(rjson)
setwd("~/Desktop/github/NYCREx/nycrex")
listingData <- fromJSON(file = 'listings.json')

listings <- do.call(rbind.data.frame, listingData)

listings$availDate = as.character(listings$availDate)
listings$listDate = as.character(listings$listDate)
listings$agent = as.character(listings$agent)
listings$brkr = as.character(listings$brkr)
listings$addr = as.character(listings$addr)
listings$title = as.character(listings$title)
listings$lat = as.double(as.character(listings$lat))
listings$lon = as.double(as.character(listings$lon))
listings$lAm = as.character(listings$lAm)
listings$geo = as.character(listings$geo)
listings$desc = as.character(listings$desc)
listings$url = as.character(listings$url)
listings$zip = as.numeric(as.character(listings$zip))
